# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Arc3D
                                 A QGIS plugin
 Tool to convert 2D lines to 3D Arcs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-17
        copyright            : (C) 2024 by Shai Sussman
        email                : shai.sussman@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Arc3D class from file Arc3D.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .arcs_3d import Arc3D
    return Arc3D(iface)
